

//轮播图
var swiper = new Swiper('.swiper-container', {
    spaceBetween: 30,
    centeredSlides: true,
    autoplay: {
        delay: 2500,
        disableOnInteraction: false,
    },
    pagination: {
        el: '.swiper-pagination',
        clickable: true,
    },
});


//搜索栏背景颜色
var sr=document.querySelector(".search");
window.onscroll=function() {
    //search部分滚动变色
    if (sr != null) {
        if (document.body.scrollTop > 115) {
            document.querySelector(".search").style.background = "transparent";
        } else {
            document.querySelector(".search").style.background = "white";
        }
    }
}
new Vue({
    el:"#mainsort",
    data:{
        ars:[
            {img:"img/1-1-1.jpg",name:"水果集市"},
            {img:"img/1-1-2.jpg",name:"苹果"},
            {img:"img/1-1-3.jpg",name:"橙子"},
            {img:"img/1-1-4.jpg",name:"奇异果"},
            {img:"img/1-1-5.jpg",name:"百香果"},
            {img:"img/1-1-6.jpg",name:"榴莲"},
            {img:"img/1-1-7.png",name:"国产水果"},
            {img:"img/1-1-8.png",name:"进口水果"}
        ],
        ars1:[
            {img:"img/1-2-1.jpg",name:"白酒"},
            {img:"img/1-2-2.jpg",name:"葡萄酒"},
            {img:"img/1-2-3.jpg",name:"啤酒"},
            {img:"img/1-2-4.jpg",name:"黄酒/养生酒"},
            {img:"img/1-2-5.jpg",name:"洋酒"}
        ],
        ars2:[
            {img:"img/1-4-1.jpg",name:"坚果炒货"},
            {img:"img/1-4-2.jpg",name:"休闲食品"},
            {img:"img/1-4-3.jpg",name:"肉干肉脯"},
            {img:"img/1-4-4.jpg",name:"蜜饯果干"},
            {img:"img/1-4-5.jpg",name:"饼干蛋糕"},
            {img:"img/1-4-6.jpg",name:"糖果/巧克力"},
            {img:"img/1-4-7.jpg",name:"膨化食品"},
            {img:"img/1-4-8.jpg",name:"中华老字号"}
        ],
        ars3:[
            {img:"img/1-6-1.jpg",name:"铁观音"},
            {img:"img/1-6-2.jpg",name:"红茶"},
            {img:"img/1-6-3.jpg",name:"绿茶"},
            {img:"img/1-6-4.jpg",name:"普洱"},
            {img:"img/1-6-5.jpg",name:"龙井"},
            {img:"img/1-6-6.jpg",name:" 养生茶"},
            {img:"img/1-6-7.jpg",name:"黑茶"}
        ],
        ars4:[
            {img:"img/1-7-1.jpg",name:"速溶咖啡"},
            {img:"img/1-7-2.jpg",name:"咖啡豆/粉"},
            {img:"img/1-7-3.jpg",name:"奶茶"},
            {img:"img/1-7-4.jpg",name:"成人奶粉"},
            {img:"img/1-7-5.jpg",name:"麦片谷物冲饮"},
            {img:"img/1-7-6.jpg",name:"代餐/谷物"}
        ],
        ars5:[
            {img:"img/1-8-1.jpg",name:"米"},
            {img:"img/1-8-2.jpg",name:"食用油"},
            {img:"img/1-8-3.jpg",name:"方便食品"},
            {img:"img/1-8-4.jpg",name:"面"},
            {img:"img/1-8-5.jpg",name:"南北干货"},
            {img:"img/1-8-6.jpg",name:"杂粮"},
            {img:"img/1-8-7.jpg",name:"调味品"},
            {img:"img/1-8-83.jpg",name:"有机食品"},
            {img:"img/1-8-9.jpg",name:"花生油"},
            {img:"img/1-8-10.jpg",name:"葵花籽油"}
        ],
        ars6:[
            {img:"img/1-3-1.jpg",name:"牛奶"},
            {img:"img/1-3-2.jpg",name:"饼干蛋糕"},
            {img:"img/1-3-3.jpg",name:"糖果/巧克力"},
            {img:"img/1-3-4.jpg",name:"方便食品"},
            {img:"img/1-3-5.jpg",name:"油"},
            {img:"img/1-3-6.jpg",name:"水"}
        ],
        ars7:[
            {img:"img/1-5-1.jpg",name:"四川"},
            {img:"img/1-5-2.jpg",name:"内蒙古"},
            {img:"img/1-5-3.jpg",name:"湖南"},
            {img:"img/1-5-4.jpg",name:"江苏"},
            {img:"img/1-5-5.png",name:"山西"},
            {img:"img/1-5-6.jpg",name:"福建"}
        ],
        ars8:[
            {img:"img/1-9-1.jpg",name:"虾类"},
            {img:"img/1-9-2.jpg",name:"鱼类"},
            {img:"img/1-9-3.jpg",name:"贝类"},
            {img:"img/1-9-4.png",name:"海产干货"},
            {img:"img/1-9-5.jpg",name:"海参"},
            {img:"img/1-9-6.jpg",name:"蟹类"},
            {img:"img/1-9-7.jpg",name:"海产加工品"}
        ],
        ar1:[
            {img:"img/2-1-1.jpg",name:"置物架"},
            {img:"img/2-1-2.jpg",name:"菜刀"},
            {img:"img/2-1-3.jpg",name:"砧板"},
            {img:"img/2-1-4.jpg",name:"DIY小工具"},
            {img:"img/2-1-5.jpg",name:"刀具套装"},
            {img:"img/2-1-6.jpg",name:"剪刀"},
            {img:"img/2-1-7.jpg",name:"瓜果刀"}
        ],
        ar2:[
            {img:"img/2-2-1.jpg",name:"置物架"},
            {img:"img/2-2-2.jpg",name:"被子"},
            {img:"img/2-2-3.jpg",name:"枕芯"},
            {img:"img/2-2-4.jpg",name:"窗帘"},
            {img:"img/2-2-5.jpg",name:"床品件套"},
            {img:"img/2-2-6.jpg",name:"电热毯"},
            {img:"img/2-2-7.jpg",name:"毛巾浴巾"}
        ],
        ar3:[
            {img:"img/2-3-1.jpg",name:"浴室用品"},
            {img:"img/2-3-2.jpg",name:"缝纫机"},
            {img:"img/2-3-3.jpg",name:"洗晒/熨烫"},
            {img:"img/2-3-4.jpg",name:"净化除味"},
            {img:"img/2-3-5.jpg",name:"雨伞雨具"}
        ],
        ar4:[
            {img:"img/2-4-1.jpg",name:"机电五金"},
            {img:"img/2-4-2.jpg",name:"工具组套"},
            {img:"img/2-4-3.jpg",name:"气动工具"},
            {img:"img/2-4-4.jpg",name:"手动工具"},
            {img:"img/2-4-5.jpg",name:"家用五金"}
        ],
        arr1:[
            {img:"img/3-1-1.jpg",name:"补水保湿"},
            {img:"img/3-1-2.jpg",name:"卸妆"},
            {img:"img/3-1-3.jpg",name:"洁面"},
            {img:"img/3-1-4.jpg",name:"爽肤水"},
            {img:"img/3-1-5.jpg",name:"乳液面霜"},
            {img:"img/3-1-6.jpg",name:"面膜"},
            {img:"img/3-1-7.jpg",name:"面部套装"},
            {img:"img/3-1-8.jpg",name:"面部护肤"}
        ],
        arr2:[
            {img:"img/3-2-1.jpg",name:"洗发"},
            {img:"img/3-2-2.jpg",name:"护发"},
            {img:"img/3-2-3.jpg",name:"染发"}
        ],
        arr3:[
            {img:"img/3-3-1.jpg",name:"补水保湿"},
            {img:"img/3-3-2.jpg",name:"沐浴"},
            {img:"img/3-3-3.jpg",name:"精油"},
            {img:"img/3-3-4.jpg",name:"香皂"},
            {img:"img/3-3-5.jpg",name:"身体护理"}
        ],
        arr4:[
            {img:"img/3-4-1.jpg",name:"口腔护理"}
        ],
        arr5:[
            {img:"img/3-5-1.jpg",name:"卫生巾"},
            {img:"img/3-5-2.jpg",name:"卫生护垫"}
        ],
        arr6:[
            {img:"img/3-6-1.jpg",name:"BB霜/气垫BB"},
            {img:"img/3-6-2.jpg",name:"女士香水"},
            {img:"img/3-6-3.jpg",name:"唇膏/彩"},
            {img:"img/3-6-4.jpg",name:"口红"},
            {img:"img/3-6-5.jpg",name:"眉笔"},
            {img:"img/3-6-6.jpg",name:"眼影"},
            {img:"img/3-6-7.jpg",name:"其他"}
        ],
        arr7:[
            {img:"img/3-7-1.jpg",name:"纸品湿巾"}
        ],
        ass:[
            {img:"img/4-1-1.jpg",name:"益智玩具"},
            {img:"img/4-1-2.jpg",name:"毛绒布艺"}
        ],
        ass1:[
            {img:"img/4-2-1.jpg",name:"NB"},
            {img:"img/4-2-2.jpg",name:"S"},
            {img:"img/4-2-3.jpg",name:"L"},
            {img:"img/4-2-4.jpg",name:"M"},
            {img:"img/4-2-5.jpg",name:"XL"},
            {img:"img/4-2-6.jpg",name:"XXL"},
            {img:"img/4-2-7.jpg",name:"拉拉裤"},
            {img:"img/4-2-8.jpg",name:"成人尿裤"},
            {img:"img/4-2-9.jpg",name:"婴儿湿巾"}
        ],
        ass2:[
            {img:"img/4-3-1.jpg",name:"1段"},
            {img:"img/4-3-2.jpg",name:"2段"},
            {img:"img/4-3-3.jpg",name:"3段"},
            {img:"img/4-3-4.jpg",name:"4段"},
            {img:"img/4-3-5.jpg",name:"孕妇奶粉"},
            {img:"img/4-3-6.jpg",name:"特殊配方奶粉"},
            {img:"img/4-3-7.jpg",name:"有机奶粉"}
        ],
        ass3:[
            {img:"img/4-4-1.jpg",name:"妈咪包/背婴带"},
            {img:"img/4-4-2.jpg",name:"产后塑性"},
            {img:"img/4-4-3.jpg",name:"文胸/内裤"},
            {img:"img/4-4-4.jpg",name:"防辐射服"},
            {img:"img/4-4-5.jpg",name:"孕妈装"},
            {img:"img/4-4-6.jpg",name:"孕期营养"},
            {img:"img/4-4-7.jpg",name:"孕期护肤"},
            {img:"img/4-4-8.jpg",name:"待产护理"},
            {img:"img/4-4-9.jpg",name:"月子装"}
        ],
        ass4:[
            {img:"img/4-5-1.jpg",name:"奶嘴奶瓶"},
            {img:"img/4-5-2.jpg",name:"吸奶器"},
            {img:"img/4-5-3.jpg",name:"暖奶消毒"},
            {img:"img/4-5-4.jpg",name:"辅食料理机"},
            {img:"img/4-5-5.jpg",name:"食物储存"},
            {img:"img/4-5-6.jpg",name:"儿童餐具"},
            {img:"img/4-5-7.jpg",name:"水壶/水杯"},
            {img:"img/4-5-8.jpg",name:"牙胶安抚"},
            {img:"img/4-5-9.jpg",name:"围兜/防溅衣"}
        ],
        a1:[
            {img:"img/5-1-1.jpg",name:"电水壶"},
            {img:"img/5-1-2.jpg",name:"电压力锅"},
            {img:"img/5-1-3.jpg",name:"电饭煲"},
            {img:"img/5-1-4.jpg",name:"电磁炉"},
            {img:"img/5-1-5.jpg",name:"微波炉"},
            {img:"img/5-1-6.jpg",name:"电饼铛"},
            {img:"img/5-1-7.jpg",name:"豆浆机"}
        ],
        a2:[
            {img:"img/5-2-1.png",name:"电吹风"},
            {img:"img/5-2-2.jpg",name:"剃须刀"},
            {img:"img/5-2-3.jpg",name:"理发器"},
            {img:"img/5-2-4.jpg",name:"脱毛器"},
            {img:"img/5-2-5.jpg",name:"口腔护理"}
        ],
        a3:[
            {img:"img/5-3-1.jpg",name:"电热水器"},
            {img:"img/5-3-2.jpg",name:"燃气热水器"},
            {img:"img/5-3-3.jpg",name:"燃气灶"},
            {img:"img/5-3-4.jpg",name:"油烟机"},
            {img:"img/5-3-5.jpg",name:"油烟套装"},
            {img:"img/5-3-6.jpg",name:"消毒柜"},
            {img:"img/5-3-7.jpg",name:"洗碗机"},
            {img:"img/5-3-8.jpg",name:"嵌入式厨电"}
        ],
        a4:[
            {img:"img/5-4-1.jpg",name:"吸尘器"},
            {img:"img/5-4-0.jpg",name:"饮水机"},
            {img:"img/5-4-2.jpg",name:"挂烫机/熨斗"},
            {img:"img/5-4-3.jpg",name:"电风扇"},
            {img:"img/5-4-4.jpg",name:"扫地机器人"},
            {img:"img/5-4-5.jpg",name:"净水器"},
            {img:"img/5-4-6.jpg",name:"取暖电器"},
            {img:"img/5-4-7.jpg",name:"插座"}
        ],
        a5:[
            {img:"img/5-5-1.jpg",name:"壁挂式空调"},
            {img:"img/5-5-2.jpg",name:"柜式空调"},
            {img:"img/5-5-3.jpg",name:"中央空调"},
            {img:"img/5-5-4.jpg",name:"空调配件"}
        ],
        a61:[
            {img:"img/6-1-1.jpg",name:"瑞表"},
            {img:"img/6-1-2.jpg",name:"国表"},
            {img:"img/6-1-3.jpg",name:"德表"},
            {img:"img/6-1-4.jpg",name:"日韩表"},
            {img:"img/6-1-5.jpg",name:"儿童手表"},
            {img:"img/6-1-6.jpg",name:"欧美表"},
            {img:"img/6-1-7.jpg",name:"智能手表"},
            {img:"img/6-1-8.jpg",name:"挂钟"},
            {img:"img/6-1-9.jpg",name:"钟表配件"},
            {img:"img/6-1-10.jpg",name:"闹钟"}
        ],
        a62:[
            {img:"img/6-2-1.jpg",name:"黄金吊坠"},
            {img:"img/6-2-2.jpg",name:"金手镯"},
            {img:"img/6-2-3.jpg",name:"纯金K金戒指"},
            {img:"img/6-2-4.jpg",name:"黄金项链"},
            {img:"img/6-2-5.jpg",name:"黄金转运珠"},
            {img:"img/6-2-6.jpg",name:"黄金耳饰"}
        ],
        a63:[
            {img:"img/6-3-1.jpg",name:"银吊坠"},
            {img:"img/6-3-2.png",name:"银耳饰"},
            {img:"img/6-3-3.jpg",name:"银戒指"},
            {img:"img/6-3-4.jpg",name:"宝宝银饰"},
            {img:"img/6-3-5.jpg",name:"银手镯"},
            {img:"img/6-3-6.jpg",name:"银脚链"}
        ],
        a64:[
            {img:"img/6-4-1.jpg",name:"项链/吊坠"},
            {img:"img/6-4-2.jpg",name:"手镯/手串"},
            {img:"img/6-4-3.jpg",name:"玉石孤品"},
            {img:"img/6-4-4.jpg",name:"翡翠玉石戒指"},
            {img:"img/6-4-5.jpg",name:"挂件/摆件"},
            {img:"img/6-4-6.jpg",name:"耳饰"}
        ],
         a65:[
            {img:"img/6-5-1.jpg",name:"钻石项链"},
            {img:"img/6-5-2.jpg",name:"裸钻"},
            {img:"img/6-5-3.jpg",name:"钻石戒指"},
            {img:"img/6-5-4.jpg",name:"钻石手镯"},
            {img:"img/6-5-5.jpg",name:"钻石耳饰"}
        ],
         a66:[
            {img:"img/6-6-1.jpg",name:"铂金戒指"},
            {img:"img/6-6-2.jpg",name:"铂金耳饰"},
            {img:"img/6-6-3.jpg",name:"铂金项链"},
            {img:"img/6-6-4.jpg",name:"铂金手镯"}
        ],
         a67:[
            {img:"img/6-7-1.jpg",name:"K金戒指"},
            {img:"img/6-7-2.jpg",name:"K金项链"},
            {img:"img/6-7-3.jpg",name:"K金手镯"},
            {img:"img/6-7-4.jpg",name:"K金耳饰"},
            {img:"img/6-7-5.jpg",name:"K金吊坠"}
        ],
        a71:[
            {img:"img/7-1-1.jpg",name:"调节免疫"},
            {img:"img/7-1-2.jpg",name:"骨骼健康"},
            {img:"img/7-1-3.jpg",name:"美容养颜"},
            {img:"img/7-1-4.jpg",name:"调节三高"},
            {img:"img/7-1-5.jpg",name:"肠胃养护"},
            {img:"img/7-1-6.jpg",name:"肝肾养护"},
            {img:"img/7-1-7.jpg",name:"美体塑身"},
            {img:"img/7-1-8.jpg",name:"缓解疲劳"},
            {img:"img/7-1-9.jpg",name:"改善睡眠"},
            {img:"img/7-1-10.jpg",name:"孕期营养"}
        ],
        a72:[
            {img:"img/7-2-1.jpg",name:"玛咖"},
            {img:"img/7-2-2.jpg",name:"蛋白质"},
            {img:"img/7-2-3.jpg",name:"维生素"},
            {img:"img/7-2-4.jpg",name:"胶原蛋白"},
            {img:"img/7-2-5.jpg",name:"左旋肉碱"},
            {img:"img/7-2-6.jpg",name:"酵素"},
            {img:"img/7-2-7.jpg",name:"益生菌"},
            {img:"img/7-2-8.jpg",name:"鱼油/磷脂"},
            {img:"img/7-2-9.jpg",name:"葡萄籽"}
        ],
        a73:[
            {img:"img/7-3-1.jpg",name:"药食同源"},
            {img:"img/7-3-2.jpg",name:"冬虫夏草"},
            {img:"img/7-3-3.jpg",name:"阿胶"},
            {img:"img/7-3-4.jpg",name:"枸杞"},
            {img:"img/7-3-5.jpg",name:"西洋参"},
            {img:"img/7-3-6.jpg",name:"燕窝"},
            {img:"img/7-3-7.jpg",name:"蜂蜜"},
            {img:"img/7-3-8.jpg",name:"三七"},
            {img:"img/7-3-10.jpg",name:"石斛/枫斗"},
            {img:"img/7-3-9.jpg",name:"养生茶饮"},
            {img:"img/7-3-11.jpg",name:"灵芝"}
        ],
        a74:[
            {img:"img/7-4-1.jpg",name:"口罩"},
            {img:"img/7-4-2.jpg",name:"眼罩/耳塞"},
            {img:"img/7-4-3.jpg",name:"跌打损伤"},
            {img:"img/7-4-4.jpg",name:"暖贴"},
            {img:"img/7-4-5.jpg",name:"鼻喉护理"},
            {img:"img/7-4-6.jpg",name:"体重秤"},
            {img:"img/7-4-7.jpg",name:"眼部保健"},
            {img:"img/7-4-8.jpg",name:"美体护理"}
        ],
        a75:[
            {img:"img/7-5-1.jpg",name:"半年抛"},
            {img:"img/7-5-2.jpg",name:"月抛"},
            {img:"img/7-5-3.jpg",name:"日抛"},
            {img:"img/7-5-4.jpg",name:"年抛"},
            {img:"img/7-5-5.jpg",name:"彩色隐形"},
            {img:"img/7-5-6.jpg",name:"护理液"},
            {img:"img/7-5-7.jpg",name:"透明隐形"},
            {img:"img/7-5-8.jpg",name:"眼睛配件"}
        ],
        a81:[
            {img:"img/8-1-1.jpg",name:"夹克"},
            {img:"img/8-1-2.jpg",name:"T恤"},
            {img:"img/8-1-3.jpg",name:"针织衫"},
            {img:"img/8-1-4.jpg",name:"衬衫"},
            {img:"img/8-1-5.jpg",name:"卫衣"},
            {img:"img/8-1-6.jpg",name:"风衣"},
            {img:"img/8-1-7.jpg",name:"牛仔裤"},
            {img:"img/8-1-8.jpg",name:"休闲裤"},
            {img:"img/8-1-9.jpg",name:"自营男装"}
        ],
        a82:[
            {img:"img/8-2-1.jpg",name:"早春新品"},
            {img:"img/8-2-2.jpg",name:"连衣裙"},
            {img:"img/8-2-3.jpg",name:"衬衫"},
            {img:"img/8-2-4.jpg",name:"T恤"},
            {img:"img/8-2-5.jpg",name:"牛仔裤"},
            {img:"img/8-2-6.jpg",name:"卫衣"},
            {img:"img/8-2-7.jpg",name:"针织衫"},
            {img:"img/8-2-8.jpg",name:"牛仔外套"},
            {img:"img/8-2-9.jpg",name:"自营女装"}
        ],
        a83:[
            {img:"img/8-3-1.jpg",name:"文胸套装"},
            {img:"img/8-3-2.jpg",name:"文胸"},
            {img:"img/8-3-3.jpg",name:"少女文胸"},
            {img:"img/8-3-4.jpg",name:"薄杯文胸"},
            {img:"img/8-3-5.jpg",name:"聚拢文胸"},
            {img:"img/8-3-6.jpg",name:"光面文胸"},
            {img:"img/8-3-7.jpg",name:"大码文胸"},
            {img:"img/8-3-8.jpg",name:"无钢圈文胸"},
            {img:"img/8-3-9.jpg",name:"运动文胸"}
        ],
        a84:[
            {img:"img/8-4-1.jpg",name:"男士腰带礼盒"},
            {img:"img/8-4-2.jpg",name:"针扣腰带"},
            {img:"img/8-4-3.jpg",name:"棒球帽"},
            {img:"img/8-4-4.jpg",name:"女士腰带礼盒"},
            {img:"img/8-4-5.jpg",name:"遮阳帽"},
            {img:"img/8-4-6.jpg",name:"礼帽"},
            {img:"img/8-4-7.jpg",name:"贝雷帽"},
            {img:"img/8-4-8.jpg",name:"鸭舌帽"},
            {img:"img/8-4-9.jpg",name:"男士围巾"},
            {img:"img/8-4-10.jpg",name:"女士围巾"},
            {img:"img/8-4-11.jpg",name:"领结/领带"},
            {img:"img/8-4-12.jpg",name:"女士披肩"},
            {img:"img/8-4-13.jpg",name:"袖扣"}
        ],
        a85:[
            {img:"img/8-5-1.jpg",name:"太阳镜"},
            {img:"img/8-5-2.jpg",name:"眼镜框"},
            {img:"img/8-5-3.jpg",name:"老花镜"},
            {img:"img/8-5-4.jpg",name:"防辐射眼镜"},
            {img:"img/8-5-5.jpg",name:"门店配镜券"},
            {img:"img/8-5-6.jpg",name:"近视太阳镜"}
        ],
        a86:[
            {img:"img/8-6-1.jpg",name:"品质童装"},
            {img:"img/8-6-2.jpg",name:"T恤"},
            {img:"img/8-6-3.jpg",name:"套装"},
            {img:"img/8-6-4.jpg",name:"裤子"},
            {img:"img/8-6-5.jpg",name:"衬衫"},
            {img:"img/8-6-6.jpg",name:"外套"}
        ],
        a91:[
            {img:"img/9-1-1.jpg",name:"运动套装"},
            {img:"img/9-1-2.jpg",name:"运动裤"},
            {img:"img/9-1-3.jpg",name:"运动T恤"},
            {img:"img/9-1-4.jpg",name:"卫衣"},
            {img:"img/9-1-5.jpg",name:"夹克/风衣"},
            {img:"img/9-1-6.jpg",name:"运动配饰"},
            {img:"img/9-1-7.jpg",name:"健身服"},
            {img:"img/9-1-8.jpg",name:"棉服"},
            {img:"img/9-1-9.jpg",name:"羽绒服"}
        ],
        a92:[
            {img:"img/9-2-1.jpg",name:"跑步鞋"},
            {img:"img/9-2-2.jpg",name:"乒羽网鞋"},
            {img:"img/9-2-3.jpg",name:"休闲鞋"},
            {img:"img/9-2-4.jpg",name:"帆布鞋"},
            {img:"img/9-2-5.jpg",name:"专项运动鞋"},
            {img:"img/9-2-6.jpg",name:"篮球鞋"},
            {img:"img/9-2-7.jpg",name:"运动包"},
            {img:"img/9-2-8.jpg",name:"足球鞋"},
            {img:"img/9-2-9.jpg",name:"训练鞋"}
        ],
        a93:[
            {img:"img/9-3-1.jpg",name:"登山鞋"},
            {img:"img/9-3-2.jpg",name:"抓绒衣裤"},
            {img:"img/9-3-3.jpg",name:"迷彩服饰"},
            {img:"img/9-3-4.jpg",name:"徒步鞋"},
            {img:"img/9-3-5.jpg",name:"户外风衣"},
            {img:"img/9-3-6.jpg",name:"速干衣裤"},
            {img:"img/9-3-7.jpg",name:"休闲鞋"},
            {img:"img/9-3-8.jpg",name:"冲锋衣裤"},
            {img:"img/9-3-9.jpg",name:"越野跑鞋"},
            {img:"img/9-3-10.jpg",name:"溯溪鞋"},
            {img:"img/9-3-11.jpg",name:"沙滩/凉拖"},
            {img:"img/9-3-12.jpg",name:"户外袜"},
            {img:"img/9-3-13.jpg",name:"功能内衣"},
            {img:"img/9-3-14.jpg",name:"工装鞋"},
            {img:"img/9-3-15.jpg",name:"软壳衣裤"}
        ],
        a94:[
            {img:"img/9-4-1.jpg",name:"乒乓球"},
            {img:"img/9-4-2.jpg",name:"羽毛球"},
            {img:"img/9-4-3.jpg",name:"轮滑滑板"},
            {img:"img/9-4-4.jpg",name:"篮球"},
            {img:"img/9-4-5.jpg",name:"台球"},
            {img:"img/9-4-6.jpg",name:"棋牌麻将"},
            {img:"img/9-4-7.jpg",name:"其他"},
            {img:"img/9-4-8.jpg",name:"足球"},
            {img:"img/9-4-9.jpg",name:"网球"}
        ],
        a101:[
            {img:"img/10-1-1.jpg",name:"单肩包"},
            {img:"img/10-1-2.jpg",name:"手提包"},
            {img:"img/10-1-3.jpg",name:"斜跨包"},
            {img:"img/10-1-4.jpg",name:"真皮包"},
            {img:"img/10-1-5.jpg",name:"双肩包"},
            {img:"img/10-1-6.jpg",name:"钱包"},
            {img:"img/10-1-7.jpg",name:"帆布包"},
            {img:"img/10-1-8.jpg",name:"水桶包"},
            {img:"img/10-1-9.jpg",name:"子母包"},
            {img:"img/10-1-10.jpg",name:"钥匙包"},
            {img:"img/10-1-11.jpg",name:"贝壳包"},
            {img:"img/10-1-12.jpg",name:"菱格包"},
            {img:"img/10-1-13.jpg",name:"红谷"},
            {img:"img/10-1-14.jpg",name:"稻草人"},
            {img:"img/10-1-15.jpg",name:"梦特娇"},
            {img:"img/10-1-16.jpg",name:"老人头"},
            {img:"img/10-1-17.jpg",name:"ELLE"},
            {img:"img/10-1-18.jpg",name:"FION"}
        ],
        a102:[
            {img:"img/10-2-1.jpg",name:"男士钱包"},
            {img:"img/10-2-2.jpg",name:"男士手包"},
            {img:"img/10-2-3.jpg",name:"单肩斜跨包"},
            {img:"img/10-2-4.jpg",name:"双肩包"},
            {img:"img/10-2-5.jpg",name:"公文包"},
            {img:"img/10-2-6.jpg",name:"男士腰带"},
            {img:"img/10-2-7.jpg",name:"帆布腰带"},
            {img:"img/10-2-8.jpg",name:"皮具礼盒"},
            {img:"img/10-2-9.jpg",name:"信封包"},
            {img:"img/10-2-10.jpg",name:"邮差包"},
            {img:"img/10-2-11.jpg",name:"帆布包"},
            {img:"img/10-2-12.jpg",name:"休闲包"},
            {img:"img/10-2-13.jpg",name:"皮尔卡丹"},
            {img:"img/10-2-14.jpg",name:"七匹狼"},
            {img:"img/10-2-15.jpg",name:"沙驰"},
            {img:"img/10-2-16.jpg",name:"TUMI"},
            {img:"img/10-2-17.jpg",name:"金利来"},
            {img:"img/10-2-18.jpg",name:"稻草人"}
        ],
        a103:[
            {img:"img/10-3-1.jpg",name:"万向轮拉杆箱"},
            {img:"img/10-3-2.jpg",name:"登机箱"},
            {img:"img/10-3-3.jpg",name:"铝框拉杆箱"},
            {img:"img/10-3-4.jpg",name:"布箱"},
            {img:"img/10-3-5.jpg",name:"儿童拉杆箱"},
            {img:"img/10-3-6.jpg",name:"女士拉杆箱"},
            {img:"img/10-3-7.jpg",name:"拉杆包"},
            {img:"img/10-3-8.jpg",name:"双肩包"},
            {img:"img/10-3-9.jpg",name:"双肩电脑包"},
            {img:"img/10-3-10.jpg",name:"新秀丽"},
            {img:"img/10-3-11.jpg",name:"法国大使"},
            {img:"img/10-3-12.jpg",name:"外交官"},
            {img:"img/10-3-13.jpg",name:"瑞动"},
            {img:"img/10-3-14.jpg",name:"威戈"},
            {img:"img/10-3-15.jpg",name:"incase"},
            {img:"img/10-3-16.jpg",name:"美旅"},
            {img:"img/10-3-17.jpg",name:"90分"},
            {img:"img/10-3-18.jpg",name:"JanSport"}
        ],
        a111:[
            {img:"img/11-1-1.jpg",name:"GUCCI"},
            {img:"img/11-1-2.jpg",name:"COACH"},
            {img:"img/11-1-3.jpg",name:"Armani"},
            {img:"img/11-1-4.jpg",name:"TAGHENER"},
            {img:"img/11-1-5.jpg",name:"RIMOWA"},
            {img:"img/11-1-6.jpg",name:"MichaelKors"},
            {img:"img/11-1-7.jpg",name:"CARTIER"},
            {img:"img/11-1-8.jpg",name:"PRADA"},
            {img:"img/11-1-9.jpg",name:"Ray-Ban"},
            {img:"img/11-1-10.jpg",name:"BURBERRY"},
            {img:"img/11-1-11.jpg",name:"FENDI"},
            {img:"img/11-1-12.jpg",name:"SalvatoreFerragamo"},
            {img:"img/11-1-13.jpg",name:"TISSOT"},
            {img:"img/11-1-14.jpg",name:"LONGINES"},
            {img:"img/11-1-15.jpg",name:"OMEGA"},
            {img:"img/11-1-16.jpg",name:"MIDO"},
            {img:"img/11-1-17.jpg",name:"周大福"},
            {img:"img/11-1-18.jpg",name:"TMARK"},
            {img:"img/11-1-19.jpg",name:"ROLEX"},
            {img:"img/11-1-20.jpg",name:"BottegaVeneta"},
            {img:"img/11-1-21.jpg",name:"Montblanc"},
            {img:"img/11-1-22.jpg",name:"Tiffany"},
            {img:"img/11-1-23.jpg",name:"Versace"},
            {img:"img/11-1-24.jpg",name:"Bally"},
            {img:"img/11-1-25.jpg",name:"ErmenegildoZegna"},
            {img:"img/11-1-26.jpg",name:"HugoBoss"},
            {img:"img/11-1-27.jpg",name:"Kenzo"},
            {img:"img/11-1-28.jpg",name:"Swarovski"},
            {img:"img/11-1-29.jpg",name:"Pandora"},
            {img:"img/11-1-30.jpg",name:"周生生"},
            {img:"img/11-1-31.jpg",name:"点睛品"},
            {img:"img/11-1-32.jpg",name:"MCM"},
            {img:"img/11-1-33.jpg",name:"Y-3"},
            {img:"img/11-1-34.jpg",name:"Longchamp"},
            {img:"img/11-1-35.jpg",name:"Furla"},
            {img:"img/11-1-36.jpg",name:"KATESPADE"},
            {img:"img/11-1-37.jpg",name:"AlexanderMcQueen"},
            {img:"img/11-1-38.jpg",name:"ToryBurch"},
            {img:"img/11-1-39.jpg",name:"通灵"},
            {img:"img/11-1-40.jpg",name:"Dolce&Gabbana"},
            {img:"img/11-1-41.jpg",name:"LaPerla"},
            {img:"img/11-1-42.jpg",name:"MOVADO"},
            {img:"img/11-1-43.jpg",name:"Valentino"},
            {img:"img/11-1-44.jpg",name:"Dunhill"},
            {img:"img/11-1-45.jpg",name:"TOUS"}
        ],
        a112:[
            {img:"img/11-2-1.jpg",name:"瑞士名表"},
            {img:"img/11-2-2.jpg",name:"箱包"},
            {img:"img/11-2-3.png",name:"钱包"},
            {img:"img/11-2-4.jpg",name:"服饰"},
            {img:"img/11-2-5.jpg",name:"腰带"},
            {img:"img/11-2-6.jpg",name:"太阳镜"},
            {img:"img/11-2-7.jpg",name:"配件"},
            {img:"img/11-2-8.jpg",name:"鞋靴"},
            {img:"img/11-2-9.jpg",name:"饰品"},
            {img:"img/11-2-10.jpg",name:"光学眼镜"},
            {img:"img/11-2-11.jpg",name:"钻石"},
            {img:"img/11-2-12.jpg",name:"奢华文具"}
        ],
        a121:[
            {img:"img/12-1-1.jpg",name:"香水"},
            {img:"img/12-1-2.jpg",name:"功能小件"},
            {img:"img/12-1-3.jpg",name:"挂件"},
            {img:"img/12-1-4.jpg",name:"车贴"},
            {img:"img/12-1-5.jpg",name:"车钥匙扣"},
            {img:"img/12-1-6.jpg",name:"车衣"},
            {img:"img/12-1-7.jpg",name:"车身装饰件"},
            {img:"img/12-1-8.jpg",name:"头枕腰靠"},
            {img:"img/12-1-9.jpg",name:"脚垫"},
            {img:"img/12-1-10.jpg",name:"方向盘套"},
            {img:"img/12-1-11.jpg",name:"坐垫坐套"},
            {img:"img/12-1-12.jpg",name:"扶手箱"}
        ],
        a122:[
            {img:"img/12-2-1.jpg",name:"毛巾掸子"},
            {img:"img/12-2-2.jpg",name:"车蜡"},
            {img:"img/12-2-3.jpg",name:"补漆笔"},
            {img:"img/12-2-4.jpg",name:"清洁剂"},
            {img:"img/12-2-5.jpg",name:"玻璃水"},
            {img:"img/12-2-6.jpg",name:"洗车水枪"},
            {img:"img/12-2-7.jpg",name:"汽车配件"},
            {img:"img/12-2-8.jpg",name:"洗车机"},
            {img:"img/12-2-9.jpg",name:"镀晶镀膜"},
            {img:"img/12-2-10.jpg",name:"底盘装甲"},
            {img:"img/12-2-11.jpg",name:"汽车贴膜"}
        ],
        a123:[
            {img:"img/12-3-1.jpg",name:"雨刷"},
            {img:"img/12-3-2.jpg",name:"添加剂"},
            {img:"img/12-3-3.jpg",name:"防冻液"},
            {img:"img/12-3-4.jpg",name:"滤清器"},
            {img:"img/12-3-5.jpg",name:"车灯"},
            {img:"img/12-3-6.jpg",name:"轮胎"},
            {img:"img/12-3-7.jpg",name:"蓄电池"},
            {img:"img/12-3-8.jpg",name:"刹车片"},
            {img:"img/12-3-9.jpg",name:"火花塞"},
            {img:"img/12-3-10.jpg",name:"轮毂"},
            {img:"img/12-3-11.jpg",name:"维修配件"},
            {img:"img/12-3-12.jpg",name:"汽修工具"},
            {img:"img/12-3-13.jpg",name:"改装配件"},
            {img:"img/12-3-14.jpg",name:"正时皮带"},
            {img:"img/12-3-15.jpg",name:"汽车喇叭"},
            {img:"img/12-3-16.jpg",name:"机油"},
            {img:"img/12-3-17.jpg",name:"减震器"},
            {img:"img/12-3-18.jpg",name:"汽车玻璃"}
        ]
        
    }
})
//分类页选显卡事件
var sortNav=document.querySelectorAll(".sort-nav>li");
//console.log(sortNav);
var sortList=document.querySelectorAll(".sort-list>div");
//console.log(sortList);
//sortList.style.display="block";
for(var i=0;i<sortNav.length;i++){
    sortNav[i].index=i;
    sortNav[i].onclick=function(){
        for(var i=0;i<sortList.length;i++){
            sortNav[i].classList.remove("color");
            sortList[i].classList.remove("act");
        }
        sortNav[this.index].classList.add("color");
        sortList[this.index].classList.add("act");
        sortList[this.index].style.backgroundColor="f5f5f5";

    }
}


var wh = window.innerHeight,
    sh0 = document.querySelector(".search1"),
    nh = document.querySelector("nav").clientHeight,
    sortnav = document.querySelector(".sortnav");
if(sh0!== null){
    var sh = sh0.clientHeight;
    console.log(wh-sh-nh);
    sortnav.style.height = wh-sh-nh+"px";
    var sortlist=document.querySelector(".sort-list");
    sortlist.style.height = wh-sh-nh+"px";
}



//弹出广告
var adp = document.querySelector(".ad p");
var adi = document.querySelector(".ad span i");
var ad = document.querySelector(".ad");
var num = Number(adi.innerHTML);
adp.addEventListener("click",function(){
    ad.style.display="none";
})
var t = setInterval(function(){
    num--;
    adi.innerHTML=num;
    if(num===0){
        ad.style.display="none";
        clearInterval(t);
    }
},1000)
//弹出广告


